---
version: '3.7'

services:
  bitmex_delta_server:
    build: .
    container_name: bitmex_delta_server
    ports:
      - "4444:4444"  # Ensure matches DELTA_SERVER_PORT
    environment:
      - TZ=utc
      - DELTA_SERVER_PORT=4444
      # - TESTNET=true
      # RESUME
      ## TODO Symbols to watch
      ## Public streams to watch
      - INSTRUMENT=true
      # - ORDERBOOKL2=true
      # - QUOTE=true
      # - TRADE=true
      ## Private streams to watch
      - EXECUTION=true
      - MARGIN=true
      - ORDER=true
      - POSITION=true
    secrets:
      - bitmex_api_key
      - bitmex_api_secret

secrets:
  bitmex_api_key:
    file: ./secrets/bitmex_api_key
  bitmex_api_secret:
    file: ./secrets/bitmex_api_secret
